[project]
name = "test-docs-private"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[dependency-groups]
docs = ["mkdocs-jupyter>=0.25.1", "mkdocs-material[imaging]>=9.6.22"]
